### PR TITLE
adapter: QueryStatusCache size metrics

### LINKED ISSUE #787: Add metrics for QueryStatusCache sizes
**Description**

The QueryStatusCache currently has 2 maps:
id_to_status: a lighter weight map that is used for query routing decisions but can grow unbounded (which may be mitigated if we switch to using a bloom/cuckoo filter at this layer: [REA-3568](https://linear.app/readyset/issue/REA-3568/use-cuckoo-filter-for-routing-decisions)).
statuses: an LruCache that stores the full query strings and has a maximum capacity, currently, of 100,000.

Having a gauge for the size of these would allow us to roughly estimate their current memory usage in the system, and allow us to observe the rate of unique queries that readyset is observing

**Change in user-visible behavior**
yes

**Requires documentation change**

yes

### PR DESCRIPTION
**Pull request by neeBis**
Having a gauge for the size of id_to_status map and statuses LruCache in the QueryStatusCache allows us to estimate current memory usage in the system and also observe the rate of unique queries that readyset is observing.
resolves #787

### CODE REVIEW

**Review by lukoktonos — CHANGES_REQUESTED** [review]
Thanks for adding the metrics! The code LGTM--it looks like there are some minor re-ordering of the `use` statements done if you run `cargo fmt`, without which our CI will fail (We are working on hooking that up to these PRs to give that feedback automatically)

Would you mind running `cargo fmt` and pushing those changes to this PR? Then I can run it through our CI and get it merged!

**Comment by neeBis** [comment]
Thanks for the review, The code is formatted now.

**Review by lukoktonos — APPROVED** [review]
Looks good! Running it through CI now and will comment on this PR once it gets merged (the PR will show as "closed" because our CI commits via a different mechanism, but you will still be marked as the author and all that good stuff).

**Comment by lukoktonos** [comment]
Merged in 5b33d1f3 🎉

**Pull request closed without merging**
